"""productrew

Revision ID: 111fc127d325
Revises: 4b204d6b57a
Create Date: 2014-10-26 02:55:18.731923

"""

# revision identifiers, used by Alembic.
revision = '111fc127d325'
down_revision = '4b204d6b57a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'image_url',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('product', 'mobileurl',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'mobileurl',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('product', 'image_url',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    ### end Alembic commands ###
