"""empty message

Revision ID: 32e21a113648
Revises: 466bce168419
Create Date: 2014-10-26 08:32:43.115441

"""

# revision identifiers, used by Alembic.
revision = '32e21a113648'
down_revision = '466bce168419'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
