"""productrew

Revision ID: 3d3da149704a
Revises: 485849305a84
Create Date: 2014-10-26 04:05:16.149284

"""

# revision identifiers, used by Alembic.
revision = '3d3da149704a'
down_revision = '485849305a84'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('size', sa.Column('gender', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('size', 'gender')
    ### end Alembic commands ###
