"""empty message

Revision ID: 438d5957d987
Revises: 54d6277fd7a7
Create Date: 2014-10-26 10:33:17.789747

"""

# revision identifiers, used by Alembic.
revision = '438d5957d987'
down_revision = '54d6277fd7a7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('sku', sa.Integer(), nullable=True))
    op.drop_column('product', 'shopsku')
    op.drop_column('product', 'shopid')
    op.drop_column('product', 'offername')
    op.alter_column('product', 'category',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('product', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('product', 'url',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'url',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('product', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('product', 'category',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.add_column('product', sa.Column('offername', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('shopid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('shopsku', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('product', 'sku')
    ### end Alembic commands ###
