"""empty message

Revision ID: 44ebbd6dab30
Revises: 32e21a113648
Create Date: 2014-10-26 08:38:34.652751

"""

# revision identifiers, used by Alembic.
revision = '44ebbd6dab30'
down_revision = '32e21a113648'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend', sa.Column('name', sa.String(length=200), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friend', 'name')
    ### end Alembic commands ###
