"""empty message

Revision ID: 466bce168419
Revises: 3d3da149704a
Create Date: 2014-10-26 08:29:40.170435

"""

# revision identifiers, used by Alembic.
revision = '466bce168419'
down_revision = '3d3da149704a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
