"""productrew

Revision ID: 485849305a84
Revises: 111fc127d325
Create Date: 2014-10-26 03:55:39.772905

"""

# revision identifiers, used by Alembic.
revision = '485849305a84'
down_revision = '111fc127d325'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('shoe_size', sa.String(length=200), nullable=True),
    sa.Column('cloth_size', sa.String(length=200), nullable=False),
    sa.Column('pant_size', sa.String(length=200), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shoe_size')
    )
    op.create_index(op.f('ix_size_date_created'), 'size', ['date_created'], unique=False)
    op.create_index(op.f('ix_size_last_updated'), 'size', ['last_updated'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_size_last_updated'), table_name='size')
    op.drop_index(op.f('ix_size_date_created'), table_name='size')
    op.drop_table('size')
    ### end Alembic commands ###
