"""product

Revision ID: 4b204d6b57a
Revises: None
Create Date: 2014-10-26 02:51:32.648718

"""

# revision identifiers, used by Alembic.
revision = '4b204d6b57a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
